---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrc-website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hrc
  template:
    metadata:
      labels:
        app: hrc
    spec:
      containers:
      - name: hrc
        image: bruceejacobs/hrc:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hrc-website-service
spec:
  selector:
    app: hrc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
